/** Auto-generated LQIP blur data URLs for next/image. */
export const blurDataURLs: Record<string, string> = {
  "/images/about/forest-balcony.avif": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAsABUB8JbAAAt+9PlHkYAD+qhqQ5fwkLlnIVh2ke3N1wJuJ34W6q0WhfoLTp8s9zDIpQAxf7SvvTg4V4/YkdlfmvtLmYAv76OEdvwAAAA==",
  "/images/about/garden-mountain.avif": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACQAQCdASoQAAkABUB8JQAAWP6Bz+AA9rgmQ/CpH89Eor+hA4M2PHwaYFK5nSR2O0041/p1OICAAA==",
  "/images/about/pavilion-grounds.avif": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoQAAwABUB8JZgCdAEEpAAAyWzlHXsd1ecYU39p4Fud7dF/03zciBhF+pBnj0AILG3Tby3UH2CzGXbMxY+e2IAA",
  "/images/care/garden-loungers.avif": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQAAkABUB8JYgCdAEejPS8AQiwAP7cpbF88RCPV+BuirJhwb2aQMmyE4HFs+lIXAM6Ipi6yGuKizQAAAA=",
  "/images/care/medical-support.avif": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAQCdASoQAAsABUB8JYwAAUUCwAD3zg0sa950dZnhzUN9mDm8Sh+Xw+Y6gq1i73VsIOfgAkPRVjHk8hZYWZ96AAA=",
  "/images/care/spa-bathroom.avif": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoJABAABUB8JQAASV9QSGAA4ZvLHqkMrysMRskOhV5SHC90nDvkAfpKBDxZbXPQrnK6AAAA",
  "/images/gallery/activity-pavilion.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwABUB8JYwAApBbQ269sgAA/TYi1tkJ2PW15050G1DBKEDMDrGkwztQZ/3vsLhkkjCu4Mqh2Lbc6tsAAA==",
  "/images/gallery/forest-desk.avif": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAQCdASoQAAwABUB8JagCdACsgxAA98zV53P9ZEZECS+gYBqbvTvuVRdpG0kIlwKEanYql1llCXU61YndJDRBGm7QzuN6p98EBJmaG5Et+AAA",
  "/images/gallery/grounds-canopy.avif": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMABAABUB8JaAC7ACQjVogAAD9JRqQ3u3AXu7RzMlLAbQItmH2dRuFQ/jagkP8TZhMUGGsB9rZz/LAa4pegAAA",
  "/images/gallery/poolside-garden.avif": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAgABUB8JYwAAq4O4SccAAD+5nuJKHXbqclj9sNLp6Lv1LaSamuz7UbND4AA",
  "/images/hero/garden-grounds.avif": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAwABUB8JaAC7AEHH8fztUEAAP5k3GsWVWt6y5NqC6dNuyrbRhJrHR2gwzK/PuKtHLOAfb2SjITi0EZ2ldMFUr0PDqgAAAA=",
  "/images/hero/villa-lap-pool.avif": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAwABUB8JbACsAEN87ClQLXgAPx2QjZ/8OM5TnOPohHP5+xWcEax/OJK5SBZ694iHZXWRGc/lAPrlA35lDCCKVDteEKLXb9l/KyYAAA=",
  "/images/life/blue-loungers.avif": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAkABUB8JbACdAEfoNclf/gA/okLqcaGFIhz/50dnhVmQuYcWSCuZg7Y50dUF/6lQEAIAAA=",
  "/images/life/communal-dining.avif": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQAAwABUB8JYgAAn/spcVZ0O4gAP7Y2LUpAeEUTrE9+rtJaoVMqUMJcu9oOgN54cdOFcahmZEgLX4mAdrX1okAAAA=",
  "/images/life/garden-jeep.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwABUB8JZAAAsQdM/dYTgAA/oEa2B3uhIaSZJahJkJ/+yKMiQ/RGu/kBaa7VJevRVNn/+g+Lz+73wAAAA==",
  "/images/location/lake-meadow.avif": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAwABUB8JbACdAEeawwrFADeBnWQj1neDhX1yEXPckF4wWWbdGJtwaM1Z4Loj3sKPaj4UoGCBDjSW4C9QAAA",
  "/images/location/lake-sunset.avif": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAwABUB8JZAAAt495rOEQAD+rtkzn2JvloJB8k16FDld7GQY8Ynr2fKuOd3CTjKHRW3r4S8vEygA",
  "/images/villas/bamboo-lounge.avif": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAwABUB8JZgCdAEJIKZF2u4AAPEgdp16O4R8bIvE0e6gL2A1+YuqrqlhRWB9y7vJu+iW6tMuIOcIy6KDk2GWJ6WC4gAA",
  "/images/villas/bedroom-daybed.avif": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMABAABUB8JbACdACwDU7awADgDKoIB6NheDyphuDvv+n95UUc4wxz7w8qAIG7YRc+oSO7Ir4bY+4JURp7t3sQ9iAAAA==",
  "/images/villas/canopy-bed.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAkABUB8JQBOgCB1HdLzi0AA/kypQO5lDK0p67Ut705p1BHde6Ry7Yf6lVhjQi3SaZNCLvSN8N0UAsAAAA==",
  "/images/villas/indoor-outdoor-bath.avif": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAwABUB8JbACdACqqONMVMgA4iiztpPMJttRBCOemmpPUm9RKdBY6aIMSblC/yCc8J22rjTjMygb1QYjx1bMI2GPsVtE7dnEmVzX/wIF8y3Av2fJAAAA",
  "/images/villas/outdoor-dining-terrace.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAwABUB8JQAAT/mXFvkAAP2UjZgavyeJ+1IB+kbx8wKWWP+pUFZJXNsQEsRHqHwkBgXPJULlqjrQA4AAAA==",
  "/images/villas/patio-lounge.avif": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkABUB8JZgAAscEOm1kQAwA+js5e9kYruj/Q2ZRbskpQufa8KeMDJiUMOIIHvRP/+sOUy6zpcAA",
  "/images/villas/veranda-dining.avif": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABUB8JQBOgCLWv4ctrEgA/s3EhwhDQZPZYGBGm3Czh+mtBoC0cib43FdfI7pTNIVl6j/5EAuLmSBhHNHNfnoYAA==",
  "/images/villas/villa-evening.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAkABUB8JYgCdAEPBbXN7T8gAP7kP6UGO7v2JbUmI2jyVPwDOFz9w7H5q28az97SGAlL4q188IkAAAAAAA==",
  "/images/villas/wellness-pavilion.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwABUB8JYwAApBbQ269sgAA/TYi1tkJ2PW150553RBMkQBvKyheXQTnplIOt/tT2mCu4Mq8I2yU8fgAAA==",
  "/images/villas/window-seat.avif": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoJABAABUB8JaACdADdoJsoAAD+5R1kafcnqpzC3ZjWZcXHPNIB7nKEvHT/oy+aEMjenbSHAAA=",
  "/images/thumbs/gallery/grounds-canopy.avif": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMABAABUB8JaAC7AC2Fa1tgAD9JRqQ3z08fQsVJepU8L84J/dwqKK5AV0fhVg2VEMlEvotv1psmLdMu+WA1xS9AAA=",
  "/images/thumbs/hero/garden-grounds.avif": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAwABUB8JaAC7AEHH8f00YQAAP5k3GsWVWt6y5NqC6dNuyrbRhJrHR2gwzK/PuKtHLOAfb2SjISJIApxlZxQL5jzb1wA",
  "/images/thumbs/hero/villa-lap-pool.avif": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAwABUB8JbACsAEPh4dSOR2PgAD8dkI2takV62Li8S9N8GRV1mXTdltf/92WnVxAMmjru4v40C69pPGLvxiNxM/nNTE723PrmhQA",
  "/images/thumbs/gallery/poolside-garden.avif": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoQAAgABUB8JYwAAq4O4JxgAP7me4knht1OSx+2Gl09F36ltJTYbHGiabQ+AAAA",
  "/images/thumbs/location/lake-sunset.avif": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAwABUB8JZAAAutsq3+EMAAA/q7ZNSlZHUyvCvmggW/973Ja/e2BbIOdGhQMJEXhV0Dvq+++XiZQAAA=",
  "/images/thumbs/villas/bedroom-daybed.avif": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoMABAABUB8JbACdAEf5TsHwAAA4AyqCAjwGxnM3shd7xJS3pvunD8RjiAQik8cxQzfjlq/IclJdj1spwP9K+YAAAA=",
  "/images/thumbs/villas/villa-evening.avif": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkABUB8JYgCdAEN68LYcuAA/uQ/pQY7u9qEl0G6eRz4euwT3i6M1lK0Tg+NPWMzEfR6Q1+uhYAA",
  "/images/thumbs/villas/indoor-outdoor-bath.avif": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAwABUB8JbACdACl+41gTUAA4iiztpPMJttRBCOemmpOPSVYOEFjpogxJuUL9raPdTwXSkfc6H8doDV2Ijlijp/ObSMMRa84cp4pwIF8y3Av2fJAAA==",
  "/images/thumbs/villas/patio-lounge.avif": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkABUB8JZgAAscEM4ZW0AD6Ozl72Riu6P9Iz04ysNpbX9Xl7zTaIVU6heMxd9u8P8NfmH11u4AA",
  "/images/thumbs/life/blue-loungers.avif": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACQAQCdASoQAAkABUB8JbACdAB+qAAA/okLqanATZC7UWlbNdladLd8DqVu4Fbm75yeBkK0bcJIZFifDIsAAA==",
  "/images/thumbs/villas/canopy-bed.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoQAAkABUB8JQBOgCB1Mcj2uQ+QAP5MqUDuZQytKeu1Le9OadQRCulxzBRR8tZPOtF9bnFpvjfhG+G6KAWAAA==",
  "/images/thumbs/gallery/forest-desk.avif": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwABUB8JagCdAD7UQP7VAAA98zV53P9Y5uaiTegBDsCoZApKettm4sxCSy4ZwFc97eO3J/lIeEI/NZ4oZDmHpzmQkqyvplZK7yAAAA=",
  "/images/thumbs/care/garden-loungers.avif": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkABUB8JYgCdABhIFZAAP7creblKZcnxxymV+0eaCLtB+DlBcoVPxfA92zoLA5VqBdZgGkhZoAA",
  "/images/thumbs/life/garden-jeep.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAwABUB8JZAAAsQbPdWyAAD+gRrYHfCalpkLIeasVH9ZSBXm5L8Bd0ZRPqQ4LKVapK47Za39B8Xn93vgAA==",
  "/images/thumbs/gallery/activity-pavilion.avif": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQAAwABUB8JYwAApBbQ27gEwAA/TYi1tkJ2XkirG20qZZuc3gdoa36koqHt67x1v9oDAGsV04CaJqiHH4AAA==",
};

export function blurFor(src: string): string | undefined {
  return blurDataURLs[src];
}
